model:
  name: "mlx-community/Llama-3.2-3B-Instruct-4bit"
  max_tokens: 512

embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

retrieval:
  top_k: 5
  min_similarity: 0.3  #Lowered threshold for better matches

generation:
  max_length: 512
  temperature: 0.7
  no_repeat_ngram_size: 2

device:
  precision: 'fp32'
  max_memory: null